name: flutter_icon_shadow
description: Adds shadow under an icon in Flutter. Customizable with color, blur and offset.
version: 2.0.7
homepage: https://github.com/chenasraf/flutter_icon_shadow

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter: null

script_runner:
  scripts:
    - docs: flutter pub global run dartdoc:dartdoc
