name: flutter_icon_shade
description: flutter icon shadow.
version: 2.0.3
homepage: https://github.com/chenasraf/flutter_flutter_icon_shade

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
